version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: feedfuse:latest
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ".:/src"

  database:
    image: postgres:15-alpine
    restart: always
    env_file: .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 30s
      retries: 60
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  scheduler:
    image: feedfuse:latest
    command: "celery --app app.crawler.worker beat --loglevel DEBUG"
    env_file: .env
    volumes:
      - ".:/src"
    depends_on:
      worker:
        condition: service_healthy

  worker:
    image: feedfuse:latest
    command: "celery --app app.crawler.worker worker -c 1 --loglevel DEBUG"
    env_file: .env
    volumes:
      - ".:/src"
    healthcheck:
      test: celery --app app.crawler.worker status
      interval: 10s
      timeout: 10s
      retries: 3
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  rabbitmq-data:
  redis-data:
