version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: feedcrawler:latest
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ".:/src"

  database:
    image: postgres:15-alpine
    restart: always
    env_file: .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 30s
      retries: 60
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
