"""Update relation

Revision ID: e19df4e26a04
Revises: 62c5317bfd41
Create Date: 2023-05-01 21:15:37.000134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19df4e26a04'
down_revision = '62c5317bfd41'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
