"""Update subscription constraint

Revision ID: 82e03bad882e
Revises: 035cd7425615
Create Date: 2023-04-29 20:23:15.276384

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "82e03bad882e"
down_revision = "035cd7425615"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_user_feed", "subscription", ["user_id", "feed_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_user_feed", "subscription", type_="unique")
    # ### end Alembic commands ###
