"""add modified_at

Revision ID: f971fe7e5d6a
Revises: 82e03bad882e
Create Date: 2023-04-30 15:03:08.117635

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f971fe7e5d6a"
down_revision = "82e03bad882e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("feed", sa.Column("modified_at", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("feed", "modified_at")
    # ### end Alembic commands ###
